### ISSUE TITLE
GAVO TAP address needs updating

### ISSUE THREAD

**Issue by lacalaca85** [konkolyseismolab/seismolab#1]
Eventually will learn github enough to solve this, but for now, the GAVO admins told me this url has been removed server-side:
service = vo.dal.TAPService("https://dc.zah.uni-heidelberg.de/__system__/tap/run/tap"

and has to be updated in query_gaia to this: 
service = vo.dal.TAPService("https://dc.zah.uni-heidelberg.de/tap"

**Comment by astrobatty** [comment]
Thanks for letting me know! :)
